name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: abz@46.242.77.215
      DEPLOY_DIRECTORY: /home/abz/apps/grpc-auth
      CONFIG_PATH: /home/abz/apps/grpc-auth/config/prod.yaml
      SSH_PORT: 34159

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Check if tag exists
        run: |
          git fetch --all --tags
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi
      - name: Deploy to VM
        run: |
          sudo apt-get install -y ssh rsync
          echo "$DEPLOY_SSH_KEY" > grpc-auth.pem
          chmod 600 grpc-auth.pem
          ssh -i grpc-auth.pem -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i grpc-auth.pem -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
#          rsync -avz -e 'ssh -i grpc-auth.pem -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no' ./migrator ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}/migrator
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Build app on server
        run: |
          ssh -i grpc-auth.pem -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "
            set -e
            cd /home/abz/apps/grpc-auth

            go mod download

            go build -o /home/abz/apps/grpc-auth/grpc-auth ./cmd/sso
            go build -o /home/abz/apps/grpc-auth/migrator ./cmd/migrator
          "
      - name: Install Redis
        run: |
          ssh -i grpc-auth.pem -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "
            sudo apt-get update && sudo apt-get install -y redis-server
            sudo systemctl enable redis-server
            sudo systemctl restart redis-server
          "
      - name: Remove old systemd service file
        run: |
          ssh -i grpc-auth.pem -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "sudo rm -f /etc/systemd/system/grpc-auth.service"
      - name: List workspace contents
        run: |
          echo "Listing deployment folder contents:"
          ls -la ${{ github.workspace }}/deployment
      - name: Copy systemd service file
        run: |
          scp -i grpc-auth.pem -P ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ github.workspace }}/deployment/grpc-auth.service ${{ env.HOST }}:/tmp/grpc-auth.service
          ssh -i grpc-auth.pem -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "sudo mv /tmp/grpc-auth.service /etc/systemd/system/grpc-auth.service"
      - name: Run migrations
        run: |
          ssh -i grpc-auth.pem -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "${{ env.DEPLOY_DIRECTORY }}/migrator --storage-path=${{ env.DEPLOY_DIRECTORY }}/sso.db --migrations-path=${{ env.DEPLOY_DIRECTORY }}/migrations"
      - name: Start application
        run: |
          ssh -i grpc-auth.pem -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "sudo systemctl daemon-reload && sudo systemctl restart grpc-auth.service"